### ISSUE TITLE
As a developer I want continuous integration run on PRs

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/vscode-hydrate#10]
It would be great to:
* Run tests
* Run linting
 
When a PR is submitted. Automated test will also help reviewers

See https://code.visualstudio.com/api/working-with-extensions/continuous-integration for more info on getting Azure Dev Ops based continuous integration going.

**Comment by samiyaakhtar** [comment]
We need to add real tests [here](https://github.com/microsoft/vscode-hydrate/blob/aa709078f7eb382c18d71d1f83f47575ac665ee9/src/test/extension.test.ts)

**Comment by samiyaakhtar** [comment]
Explore the best practices for continuous integrations in VS code extensions
